language: node_js
node_js:
- '8'
dist: trusty
sudo: false
install:
- npm install
script:
- npm run code-check
- npm run build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: W515IQ/uWVjtbyPspjJNRuD3IGj/kiU3knCKa3ggCwVn3ASgfWOt6ijnGdhgtzS0mj+I57xQ4SlcP37lfmA6O/HZqClumiU4bbyjM0BTtSlecdgOum+Ig6UNAlAKYXvMDWNfHjBsWOWPCaHAd0/NvSPav316zP3a0DfUCmAW6a7QGzLfZDe7NEQdVUg2pzYGfGVbIeQBK228vWAC3cQjP/ZWvdwqfoNTdmGMgkw3GTP0fSSLJ6VPLrQC053Tm5gznmN7Dkq6jrlMQTIKUFKsX1cjO9wOGDZY3lA1vhBYS5yZfwmmV3q4xV9hQDcdaA78rctU63pl7acRAueKuigxHd2JzWYtgydUYwyMD8sXXtC3PWjkgb/vgmv3Mpl0okB63DrYm4XTrGZBsVrLh1X+0u0SGLbAZubLXnk1/0bLCpTOPfenzzB2tnV9hVbZqEZnldKySkOC30vIFDOCedLdUMx4u+hty1jfmX/AKAJSweehfnDWeO1HjSogbOLblDZ/Ve81qb0vRpbnfu4uQrq4zHgHQpa+oVjUqOr9GY5jwGD9dyjsswPPKKLcIp6AdP2/4eA0/Oa8YA7Mdpg62vywwOjDPb4zXyX0oAY/J+D+cd1XN0WszixMeypoYWx4rkwZJJ7xlk02SXEdo/cgTtGJ28IFplvlrZb9EJd+uap6QEY=
  on:
    branch: master
    repo: Cimpress/cimpress-translations-cli
